### ISSUE TITLE
Feature Request: Add Validators for languages in Biblica data

### ISSUE THREAD

**Issue by JRMeyer** [ftyers/commonvoice-utils#19]
these languages are on https://open.bible/, but aren't in covo... yet:)

[Akuapem Twi](https://en.wikipedia.org/wiki/Akuapem_dialect)
[Asante Twi](https://en.wikipedia.org/wiki/Asante_dialect)
[Chichewa](https://en.wikipedia.org/wiki/Chewa_language)
[Ewe](https://en.wikipedia.org/wiki/Ewe_language)
[Kikuyu](https://en.wikipedia.org/wiki/Kikuyu_language)
[Lingala](https://en.wikipedia.org/wiki/Lingala)
[Luo](https://en.wikipedia.org/wiki/Dholuo)
[Sorani Kurdi](https://en.wikipedia.org/wiki/Sorani)

**Comment by ftyers** [comment]
- [ ] Akuapem Twi
- [ ] Asante Twi
- [ ] Chichewa
- [ ] Ewe - 44d5fd2
- [ ] Kikuyu
- [ ] Lingala
- [ ] Luo
- [ ] Sorani Kurdi

**Comment by ftyers** [comment]
Should check Twi with respect to how variation is done. New issues welcome.

**Comment by ftyers** [comment]
All are now done :) Feedback and new issues welcome!
