### ISSUE TITLE
Ukrainian needs apostrophe

### ISSUE THREAD

**Issue by JRMeyer** [ftyers/commonvoice-utils#2]
the apostrophe is needed to write Ukrainian, as in `ім'я` ("name")

https://en.wiktionary.org/wiki/%D1%96%D0%BC%27%D1%8F#Ukrainian

h/t @robinhad

**Comment by ftyers** [comment]
Thanks @JRMeyer ! Which is Unicode character they prefer? Modifier letter apostrophe or plain apostrophe?

**Comment by JRMeyer** [comment]
that I don't know... @robinhad ?

**Comment by ftyers** [comment]
Wikipedia suggests [Modifier letter apostrophe](https://en.wikipedia.org/wiki/Ukrainian_alphabet), but I can use a validation step to normalise the other common ones to that.

**Comment by robinhad** [comment]
@ftyers, it could be either one or another
also some words contain dash "-" character inside, such as "аби-який", "прем'єр-міністр"

**Comment by robinhad** [comment]
in my training run of DeepSpeech I used Modified letter apostrophe, I think it reads better
I think validation step would be a great place to normalize to that

**Comment by ftyers** [comment]
Fixed in 76dd7b6. :)
