### ISSUE TITLE
missing Hausa characters

### ISSUE THREAD

**Issue by JRMeyer** [ftyers/commonvoice-utils#20]
these look like valid Hausa characters, but `covo validate ha` will either remove them or fail on them

`’`
`ā`
`ă`

**Comment by ftyers** [comment]
In general, according to the [Wikipedia page](https://en.wikipedia.org/wiki/Hausa_language#Tones):
> In standard written Hausa, tone is not marked. In recent linguistic and pedagogical materials, tone is marked by means of diacritics. 
Does the data you have mark those?

**Comment by ftyers** [comment]
I added them in 38b92b5. It seems those are non-standard diacritic marks, but we can update this if we get a different dataset.
