### ISSUE TITLE
hindi encoding issue

### ISSUE THREAD

**Issue by treya-lin** [ftyers/commonvoice-utils#23]
Hi. I tried using the g2p tool to phonemize hindi words, but there was some encoding issues.

`from cvutils import Phonemiser`
`p = Phonemiser('hi')`
`p.phonemise('अवकाशग्रहण')`

At first, the error message was like:

UnicodeDecodeError                        Traceback (most recent call last)
C:\Users\MAGICD~1\AppData\Local\Temp/ipykernel_10860/951158175.py in <module>
      1 from cvutils import Phonemiser
----> 2 p = Phonemiser('hi')
      3 p.phonemise('अवकाशग्रहण')

~\Anaconda3\lib\site-packages\cvutils\phonemiser.py in __init__(self, lang)
     22                         print('[Phonemiser] Function not implemented', file=sys.stderr)
     23                 try:
---> 24                         self.validator = Validator(self.lang)
     25                 except FileNotFoundError:
     26                         pass

~\Anaconda3\lib\site-packages\cvutils\validator.py in __init__(self, lang)
     13                 self.nfkd = False
     14                 try:
---> 15                         self.load_data()
     16                 except FileNotFoundError:
     17                         print('[Validator] Function not implemented', file=sys.stderr)

~\Anaconda3\lib\site-packages\cvutils\validator.py in load_data(self)
     24                 self.lower = False
     25                 data_dir = os.path.abspath(os.path.dirname(__file__)) + '/data/'
---> 26                 **for line in open(data_dir + self.lang + '/validate.tsv').readlines():**
     27                         if line[0] == '#':
     28                                 continue

**UnicodeDecodeError: 'gbk' codec can't decode byte 0x98 in position 50: illegal multibyte sequence**

Then I set encoding='utf-8 in the line 26 of '~\Anaconda3\lib\site-packages\cvutils\validator.py' , but  it didn't work. It still went like:

UnicodeDecodeError                        Traceback (most recent call last)
...
~\Anaconda3\lib\site-packages\cvutils\validator.py in load_data(self)
     24                 self.lower = False
     25                 data_dir = os.path.abspath(os.path.dirname(__file__)) + '/data/'
---> 26                 for line in open(data_dir + self.lang + '/validate.tsv',**encoding='utf-8'**).readlines():
     27                         if line[0] == '#':
     28                                 continue

**UnicodeDecodeError: 'gbk' codec can't decode byte 0x98 in position 50: illegal multibyte sequence**

Is there anything I did wrong? And I wonder is there any other method to solve the encoding issue? Thanks!

**Comment by ftyers** [comment]
Dear @treya-lin, thank you for your report. This looks like an [encoding issue](https://github.com/ftyers/commonvoice-utils/blob/main/doc/TROUBLESHOOTING.md), could you check you have a UTF-8 compatible locale?

**Comment by treya-lin** [comment]
> Dear @treya-lin, thank you for your report. This looks like an [encoding issue](https://github.com/ftyers/commonvoice-utils/blob/main/doc/TROUBLESHOOTING.md), could you check you have a UTF-8 compatible locale? Btw, the Hindi phonemiser is not great.

Hi @ftyers  thank you for your reply. I have been using utf-8 in python to read files for a long time, so I assume my utf-8 compatible locale is fine right?

**Comment by treya-lin** [comment]
> Dear @treya-lin, thank you for your report. This looks like an [encoding issue](https://github.com/ftyers/commonvoice-utils/blob/main/doc/TROUBLESHOOTING.md), could you check you have a UTF-8 compatible locale? Btw, the Hindi phonemiser is not great.

Dear @ftyers I assume I do have the utf-8 compatible locale as I have been using utf-8 in python to read files for a long time. Is this what you meant?
And I also tried the following commad:
`(base) PS D:\> python -c "import sys; print (sys.stdout.encoding)"`
`utf-8`

**Comment by ftyers** [comment]
Hmm, there is also a `FileNotFound` exception. Could you format the error message more clearly (maybe using ```?)
