### ISSUE TITLE
Issue with encoding during setup in Windows

### ISSUE THREAD

**Issue by HarikalarKutusu** [ftyers/commonvoice-utils#29]
This happened when I try to pip install it in the Windows Anaconda cmd (Windows 10 US English version, Python 3.9 and 3.8 tested).

```
c:\Users\xxxx> pip install git+https://github.com/ftyers/commonvoice-utils.git
Collecting git+https://github.com/ftyers/commonvoice-utils.git
  Cloning https://github.com/ftyers/commonvoice-utils.git to c:\temp1\pip-req-build-06f01lti
  Running command git clone -q https://github.com/ftyers/commonvoice-utils.git 'C:\TEMP1\pip-req-build-06f01lti'
  Resolved https://github.com/ftyers/commonvoice-utils.git to commit c738e7f8031cd2e1ca83fdbd6dd3e8a5db1ad583
    ERROR: Command errored out with exit status 1:
     command: 'D:\Anaconda\Anaconda3\envs\p39_c112\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\TEMP1\\pip-req-build-06f01lti\\setup.py'"'"'; __file__='"'"'C:\\TEMP1\\pip-req-build-06f01lti\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\TEMP1\pip-pip-egg-info-mvngstdl'
         cwd: C:\TEMP1\pip-req-build-06f01lti\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\TEMP1\pip-req-build-06f01lti\setup.py", line 8, in <module>
        README = (HERE / "README.md").read_text()
      File "D:\Anaconda\Anaconda3\envs\p39_c112\lib\pathlib.py", line 1267, in read_text
        return f.read()
      File "D:\Anaconda\Anaconda3\envs\p39_c112\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2697: character maps to <undefined>
    ----------------------------------------
WARNING: Discarding git+https://github.com/ftyers/commonvoice-utils.git. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

It seems setup.py needs to configure encoding as UTF-8, but I'm a noob here...

**Comment by ftyers** [comment]
Yeah:

```
      File "D:\Anaconda\Anaconda3\envs\p39_c112\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
```

This is a bad sign, it's trying to use [Windows-1252](https://en.wikipedia.org/wiki/Windows-1252). It looks like a problem with Python/Anaconda/Setup rather than anything specific in `covo`.

There are a few hacks, e.g. [here](https://stackoverflow.com/questions/31469707/changing-the-locale-preferred-encoding-in-python-3-in-windows/34345136#34345136) and [here](https://stackoverflow.com/questions/31469707/changing-the-locale-preferred-encoding-in-python-3-in-windows). 

I've not used Window so much and have no way of testing, but if you could try one of those and let me know if it works that would be great!

**Comment by HarikalarKutusu** [comment]
This Python locale thing in Windows is a bummer for Turkish. I even could not get a working lower() and correct sorting for Turkish.
```
print("ÜĞİŞÇÖ I".lower())
```
outputs
> üği̇şçö i

it should be
> üği̇şçö ı

On the other hand, those hacks are for Python environment and not for Windows cmd. But, fortunately, I upgraded my 3 yo Win version last week and just found a new beta feature, which solved my problem. The information is in this post:

https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window
