### ISSUE TITLE
Add single digits and yes / no?

### ISSUE THREAD

**Issue by JRMeyer** [ftyers/commonvoice-utils#3]
thinking it would be useful to add digits and yes / no from https://github.com/JRMeyer/common-voice-stats#single-digit-numbers--yes--no

thoughts?

**Comment by ftyers** [comment]
That's a great idea! What do you think? A `vocab.tsv` file? How would it be exposed? Under `Alphabet` or some other module?

**Comment by ftyers** [comment]
Added in 0b76994, I made a new class for Corpora.

**Comment by ftyers** [comment]
You can use it like this:
```python
        >>> c = Corpus('sah')
        >>> c.dump_url()
        'https://dumps.wikimedia.org/sahwiki/latest/sahwiki-latest-pages-articles.xml.bz2'
        >>> c = Corpus('cv')
        >>> c.target_segments()
        ['пӗрре', 'иккӗ', 'виҫҫӗ', 'тӑваттӑ', 'пиллӗк', 'улттӑ', 'ҫиччӗ', 'саккӑр', 'тӑххӑр', 'вуннӑ', 'ҫапла', 'ҫук']
```
