### ISSUE TITLE
covo is not portable

### ISSUE THREAD

**Issue by HarikalarKutusu** [ftyers/commonvoice-utils#36]
The argument structure of covo is position based. Therefore it only works on some systems where covo is called directly as:
```
covo [arguments]
```
On Windows, you need to invoke the related python executable if not in path like:
```
python3 covo [arguments]
```
This changes the argument indexes and covo fails.

If an argument parser is added, there will be not such an issue. Currently, I need to open a VM (or use WSL) to just get an alphabet for example.

**Comment by ftyers** [comment]
Thanks for reporting this issue!

I've not used Windows in a long time, and do not like the standard Python argument parser libraries. I think this could be taken care of by looking at the name of the first command, and if it includes `python` then basically adding an offset.

**Comment by HarikalarKutusu** [comment]
> Thanks for reporting this issue!
> 
> I've not used Windows in a long time, and do not like the standard Python argument parser libraries. I think this could be taken care of by looking at the name of the first command, and if it includes `python` then basically adding an offset.

Exactly the quick solution I thought... I can give a hand if you like...
