### ISSUE TITLE
Feature Request: Please add "hasValidator" etc

### ISSUE THREAD

**Issue by HarikalarKutusu** [ftyers/commonvoice-utils#37]
Currently commonvoice-utils returns a list of paths if you want to check if e.g. segmentation is supported by a language, thus you need to scan the list to get a result. Like:

```py
import cvutils as cvu

cv: cvu.CV = cvu.CV()

lc = 'tr'
supported: bool = False

validator: cvu.Validator = cvu.Validator(lc)
tokeniser: cvu.Tokeniser = cvu.Tokeniser(lc)

for val in cv.validators():
    if lc == os.path.split(os.path.split(val)[0])[1]:
        supported = True

```

It would be very helpful to have utility functions like cvu.hasValidator(lc) or cvu.hasTokenizer(lc) which does the same out of the box.

**Comment by ftyers** [comment]
Hmm... at the moment it works like this:

```python
import cvutils as cvu

cv: cvu.CV = cvu.CV()

print('tr' in cv.validators())
print('nhi' in cv.validators())
```

```
$ python3 /tmp/test.py
True
False
```

But we could definitely implement some utility functions too, they should probably go in `__init__.py`.

**Comment by HarikalarKutusu** [comment]
> Hmm... at the moment it works like this:

Oh, of course :) Thanks...

**Comment by HarikalarKutusu** [comment]
Sure, thanks for the tip...
