### ISSUE TITLE
Turkish abbr not merged

### ISSUE THREAD

**Issue by HarikalarKutusu** [ftyers/commonvoice-utils#38]
I might have messed up with that because I had git misfortune, deleted and re forked/re-cloned the repo.

Therefore the following commit seems not be merged:
https://github.com/HarikalarKutusu/commonvoice-utils/blob/c471900a7591737bd3e451476623e6b414729256/cvutils/data/tr/abbr.tsv

If it is not accessible by you, I can create another PR for it. Please advise.

**Comment by ftyers** [comment]
No problem, I've committed it in 21adfed.
